export const homeData = [
  {
    id: 1,
    name: "LOVE DEATH + ROBOTS",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Criaturas aterrorizantes, surpresas bizarras e humor ácido habitam e florescem de cada um dos vários universos únicos criados para essa coletânea de curtas de animação, em que cada episódio apresenta sua própria narrativa e estilo visual.",
    starring: "Madeleine Knight, Mary Elizabeth",
    genres: "Action",
    tags: "Action, Animation, Horror",
    cover: "src/assets/images/home1.jpg",
    video: "https://www.youtube.com/embed/uD-242dcxRE",
    date: "15-Mar-2019",
  },
  {
    id: 2,
    name: "Guardians of the Galaxy",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "O aventureiro do espaço Peter Quill torna-se presa de caçadores de recompensas depois que rouba a esfera de um vilão traiçoeiro, Ronan. Para escapar do perigo, ele faz uma aliança com um grupo de quatro extraterrestres.",
    starring: "Chris Pratt, Zoë Saldaña",
    genres: "Adventures",
    tags: "Adventures, Action",
    cover: "src/assets/images/home2.jpg",
    video: "https://www.youtube.com/embed/wUn05hdkhjM",
    date: "31-Jul-2014",
  },
  {
    id: 3,
    name: "The Mandalorian",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Um atirador solitário explora os confins da galáxia, longe da autoridade da Nova República.",
    starring: "Pedro Pascal, Gina Carano",
    genres: "Adventures",
    tags: "Adventures, Action",
    cover: "src/assets/images/home3.jpg",
    video: "https://www.youtube.com/embed/aOC8E8z_ifw",
    date: "12-Nov-2019",
  },
  {
    id: 4,
    name: "The Suicide Squad",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "O governo envia os supervilões mais perigosos do mundo para a remota ilha de Corto Maltese, repleta de inimigos. Armados com armas de alta tecnologia, eles viajam pela selva perigosa em uma missão de busca e destruição com o Coronel Rick Flag.",
    starring: "Margot Robbie, Pete Davidson",
    genres: "Action",
    tags: "Drama, Horror",
    cover: "src/assets/images/home4.jpg",
    video: "https://www.youtube.com/embed/UkFJ90ef4_I",
    date: "05-Ago-2021",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "src/assets/images/upcome/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "src/assets/images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "src/assets/images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "src/assets/images/upcome/u4.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "src/assets/images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "src/assets/images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "src/assets/images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "src/assets/images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "src/assets/images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "src/assets/images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "src/assets/images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "src/assets/images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "src/assets/images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "src/assets/images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "src/assets/images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "src/assets/images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "src/assets/images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "src/assets/images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]
